In [88]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [89]:
df = pd.read_csv("student_performance.csv")

In [90]:
print(df)

    Student_ID  Gender  Age  Study_Hours  Attendance  Marks Department
0         1001    Male   19            3          78     68         CS
1         1002  Female   20            5          92     84         IT
2         1003    Male   19            2          65     55         CS
3         1004  Female   21            6          95     91         IT
4         1005    Male   20            4          84     73         CS
5         1006  Female   19            7          97     95         IT
6         1007    Male   22            3          73     64         CS
7         1008  Female   20            5          89     82         IT
8         1009    Male   21            2          61     51         CS
9         1010  Female   19            8          98     97         IT
10        1011    Male   20            4          80     70         CS
11        1012  Female   21            6          91     88         IT
12        1013    Male   19            3          76     62         CS
13        1014  Female   20            5          88     79         IT
14        1015    Male   22            2          68     58         CS
15        1016  Female   19            7          96     93         IT
16        1017    Male   21            4          82     75         CS
17        1018  Female   20            6          94     90         IT
18        1019    Male   19            3          71     60         CS
19        1020  Female   22            5          86     81         IT

In [91]:
df.shape

(20, 7)

In [92]:
df.columns

Index(['Student_ID', 'Gender', 'Age', 'Study_Hours', 'Attendance', 'Marks',
       'Department'],
      dtype='object')

In [93]:
df.dtypes

Student_ID      int64
Gender         object
Age             int64
Study_Hours     int64
Attendance      int64
Marks           int64
Department     object
dtype: object

In [94]:
df.isnull()

    Student_ID  Gender    Age  Study_Hours  Attendance  Marks  Department
0        False   False  False        False       False  False       False
1        False   False  False        False       False  False       False
2        False   False  False        False       False  False       False
3        False   False  False        False       False  False       False
4        False   False  False        False       False  False       False
5        False   False  False        False       False  False       False
6        False   False  False        False       False  False       False
7        False   False  False        False       False  False       False
8        False   False  False        False       False  False       False
9        False   False  False        False       False  False       False
10       False   False  False        False       False  False       False
11       False   False  False        False       False  False       False
12       False   False  False        False       False  False       False
13       False   False  False        False       False  False       False
14       False   False  False        False       False  False       False
15       False   False  False        False       False  False       False
16       False   False  False        False       False  False       False
17       False   False  False        False       False  False       False
18       False   False  False        False       False  False       False
19       False   False  False        False       False  False       False

In [95]:
df.describe()

       Student_ID        Age  Study_Hours  Attendance      Marks
count    20.00000  20.000000    20.000000   20.000000  20.000000
mean   1010.50000  20.150000     4.500000   83.200000  75.800000
std       5.91608   1.089423     1.791794   11.311848  14.299798
min    1001.00000  19.000000     2.000000   61.000000  51.000000
25%    1005.75000  19.000000     3.000000   75.250000  63.500000
50%    1010.50000  20.000000     4.500000   85.000000  77.000000
75%    1015.25000  21.000000     6.000000   92.500000  88.500000
max    1020.00000  22.000000     8.000000   98.000000  97.000000

In [96]:
df["Study_Hours"].mean()

np.float64(4.5)

In [97]:
df["Marks"].mean()

np.float64(75.8)

In [98]:
df["Marks"].max()

97

In [99]:
df

    Student_ID  Gender  Age  Study_Hours  Attendance  Marks Department
0         1001    Male   19            3          78     68         CS
1         1002  Female   20            5          92     84         IT
2         1003    Male   19            2          65     55         CS
3         1004  Female   21            6          95     91         IT
4         1005    Male   20            4          84     73         CS
5         1006  Female   19            7          97     95         IT
6         1007    Male   22            3          73     64         CS
7         1008  Female   20            5          89     82         IT
8         1009    Male   21            2          61     51         CS
9         1010  Female   19            8          98     97         IT
10        1011    Male   20            4          80     70         CS
11        1012  Female   21            6          91     88         IT
12        1013    Male   19            3          76     62         CS
13        1014  Female   20            5          88     79         IT
14        1015    Male   22            2          68     58         CS
15        1016  Female   19            7          96     93         IT
16        1017    Male   21            4          82     75         CS
17        1018  Female   20            6          94     90         IT
18        1019    Male   19            3          71     60         CS
19        1020  Female   22            5          86     81         IT

In [100]:
df["Marks"] == 97

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: Marks, dtype: bool

In [101]:
df.loc[9]

Student_ID       1010
Gender         Female
Age                19
Study_Hours         8
Attendance         98
Marks              97
Department         IT
Name: 9, dtype: object

In [102]:
df["Department"].value_counts()

Department
CS    10
IT    10
Name: count, dtype: int64

In [103]:
cs = (df["Department"] == "CS")
df[cs]

    Student_ID Gender  Age  Study_Hours  Attendance  Marks Department
0         1001   Male   19            3          78     68         CS
2         1003   Male   19            2          65     55         CS
4         1005   Male   20            4          84     73         CS
6         1007   Male   22            3          73     64         CS
8         1009   Male   21            2          61     51         CS
10        1011   Male   20            4          80     70         CS
12        1013   Male   19            3          76     62         CS
14        1015   Male   22            2          68     58         CS
16        1017   Male   21            4          82     75         CS
18        1019   Male   19            3          71     60         CS

In [104]:
df[cs]["Marks"].mean()

np.float64(63.6)

In [105]:
IT = (df["Department"] == "IT")
df[IT]

    Student_ID  Gender  Age  Study_Hours  Attendance  Marks Department
1         1002  Female   20            5          92     84         IT
3         1004  Female   21            6          95     91         IT
5         1006  Female   19            7          97     95         IT
7         1008  Female   20            5          89     82         IT
9         1010  Female   19            8          98     97         IT
11        1012  Female   21            6          91     88         IT
13        1014  Female   20            5          88     79         IT
15        1016  Female   19            7          96     93         IT
17        1018  Female   20            6          94     90         IT
19        1020  Female   22            5          86     81         IT

In [106]:
df[IT]["Marks"].mean()

np.float64(88.0)

In [107]:
df["Gender"].value_counts()

Gender
Male      10
Female    10
Name: count, dtype: int64

In [110]:
Male = df["Gender"] == "Male"
df[Male]["Marks"].mean()

np.float64(63.6)

In [112]:
Female = df["Gender"] == "Female"
df[Female]["Marks"].mean()

np.float64(88.0)

In [115]:
df["Study_Hours"].max()

8

In [116]:
df["Study_Hours"].min()

2

In [117]:
df["Study_Hours"].mean()

np.float64(4.5)

In [118]:
df["Attendance"].max()

98

In [119]:
df["Attendance"].min()

61

In [120]:
df["Attendance"].mean()

np.float64(83.2)

In [125]:
Top_Performers = df["Marks"]>=80

In [126]:
Top_Performers

0     False
1      True
2     False
3      True
4     False
5      True
6     False
7      True
8     False
9      True
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19     True
Name: Marks, dtype: bool

In [127]:
Top_Performers.sum()

np.int64(9)

In [129]:
Attendance = df["Attendance"]>=90
Attendance.sum()

np.int64(7)

In [143]:
High_Attendance__Marks = (df["Attendance"]>=90) & (df["Marks"]>=80)
High_Attendance__Marks.sum()

np.int64(7)

In [152]:
df[df["Attendance"]>=90]["Marks"].mean()

np.float64(91.14285714285714)

In [154]:
df[df["Attendance"]>=90]["Marks"].max()

97

In [155]:
df[df["Study_Hours"]>=5]["Marks"].mean()

np.float64(88.0)

In [156]:
df[df["Study_Hours"]>=5]["Marks"].min()

79

In [157]:
df[df["Study_Hours"]>=5]["Marks"].max()

97

In [160]:
df[df["Gender"] == "Female"]["Marks"].min()

79

In [161]:
df[df["Gender"] == "Female"]["Marks"].max()

97

In [162]:
df[df["Gender"] == "Male"]["Marks"].mean()

np.float64(63.6)

In [163]:
df[df["Gender"] == "Male"]["Marks"].max()

75

In [164]:
df[df["Department"] == "IT"]["Marks"].min()

79

In [166]:
df[df["Department"] == "CS"]["Attendance"].max()

84

In [167]:
df[df["Department"] == "CS"]["Attendance"].mean()

np.float64(73.8)